function write_metrics_tex(tex_path, T_valid)
%WRITE_METRICS_TEX Export metrics summary as LaTeX macros.
%
%   eit_validation.write_metrics_tex(tex_path, T_valid)
%
%   Inputs:
%     tex_path - Output .tex file path
%     T_valid  - Results table (only valid rows)

    n = height(T_valid);

    fid = fopen(tex_path, 'w');
    if fid < 0
        error('Could not write: %s', tex_path);
    end

    fprintf(fid, '%% Auto-generated by batch_validate.m on %s\n', datestr(now, 31));
    fprintf(fid, '%% Metrics: CC[-1,1] SSIM[0,1] GRE[0,inf) RMSE[0,1] PSNR[dB]\n');
    fprintf(fid, '%% Ideal values: CC=1, SSIM=1, GRE=0, RMSE=0, PSNR=inf\n\n');
    fprintf(fid, '\\newcommand{\\NMatlabDatasets}{%d}\n\n', n);

    % EIDORS metrics (Gauss-Newton + Tikhonov)
    fprintf(fid, '%% EIDORS (Gauss-Newton + Tikhonov)\n');
    fprintf(fid, '\\newcommand{\\EidorsCCMean}{%.2f}\n',   mean(T_valid.CC_E,   'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsCCSD}{%.2f}\n',     std(T_valid.CC_E,   0, 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsSSIMMean}{%.2f}\n', mean(T_valid.SSIM_E, 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsSSIMSD}{%.2f}\n',   std(T_valid.SSIM_E, 0, 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsGREMean}{%.2f}\n',  mean(T_valid.GRE_E,  'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsGRESD}{%.2f}\n',    std(T_valid.GRE_E,  0, 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsRMSEMean}{%.2f}\n', mean(T_valid.RMSE_E, 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsRMSESD}{%.2f}\n',   std(T_valid.RMSE_E, 0, 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsPSNRMean}{%.2f}\n', mean(T_valid.PSNR_E, 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsPSNRSD}{%.2f}\n\n', std(T_valid.PSNR_E, 0, 'omitnan'));

    % MATLAB LBP metrics
    fprintf(fid, '%% MATLAB LBP\n');
    fprintf(fid, '\\newcommand{\\MatlabCCMean}{%.2f}\n',   mean(T_valid.CC_M,   'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabCCSD}{%.2f}\n',     std(T_valid.CC_M,   0, 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabSSIMMean}{%.2f}\n', mean(T_valid.SSIM_M, 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabSSIMSD}{%.2f}\n',   std(T_valid.SSIM_M, 0, 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabGREMean}{%.2f}\n',  mean(T_valid.GRE_M,  'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabGRESD}{%.2f}\n',    std(T_valid.GRE_M,  0, 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabRMSEMean}{%.2f}\n', mean(T_valid.RMSE_M, 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabRMSESD}{%.2f}\n',   std(T_valid.RMSE_M, 0, 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabPSNRMean}{%.2f}\n', mean(T_valid.PSNR_M, 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabPSNRSD}{%.2f}\n',   std(T_valid.PSNR_M, 0, 'omitnan'));

    fclose(fid);
end
