function write_metrics_tex(tex_path, T_valid)
%WRITE_METRICS_TEX Export metrics summary as LaTeX macros.
%
%   eit_validation.write_metrics_tex(tex_path, T_valid)
%
%   Inputs:
%     tex_path - Output .tex file path
%     T_valid  - Results table (only valid rows)

    n = height(T_valid);

    fid = fopen(tex_path, 'w');
    if fid < 0
        error('Could not write: %s', tex_path);
    end

    fprintf(fid, '%% Auto-generated by batch_validate.m on %s\n', datestr(now, 31));
    fprintf(fid, '%% Metrics: CC[-1,1] SSIM[0,1] GRE[0,inf) RMSE[0,1] PSNR[dB]\n');
    fprintf(fid, '%% Ideal values: CC=1, SSIM=1, GRE=0, RMSE=0, PSNR=inf\n\n');
    fprintf(fid, '\\newcommand{\\NMatlabDatasets}{%d}\n\n', n);

    % EIDORS metrics
    fprintf(fid, '%% EIDORS (Gauss-Newton + Tikhonov)\n');
    fprintf(fid, '\\newcommand{\\EidorsCCMean}{%.4f}\n', mean(T_valid.CC_E, 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsCCMin}{%.4f}\n', min(T_valid.CC_E, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsCCMax}{%.4f}\n', max(T_valid.CC_E, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsSSIMMean}{%.4f}\n', mean(T_valid.SSIM_E, 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsSSIMMin}{%.4f}\n', min(T_valid.SSIM_E, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsSSIMMax}{%.4f}\n', max(T_valid.SSIM_E, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsGREMean}{%.4f}\n', mean(T_valid.GRE_E, 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsGREMin}{%.4f}\n', min(T_valid.GRE_E, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsGREMax}{%.4f}\n', max(T_valid.GRE_E, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsRMSEMean}{%.4f}\n', mean(T_valid.RMSE_E, 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsRMSEMin}{%.4f}\n', min(T_valid.RMSE_E, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsRMSEMax}{%.4f}\n', max(T_valid.RMSE_E, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsPSNRMean}{%.2f}\n', mean(T_valid.PSNR_E, 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsPSNRMin}{%.2f}\n', min(T_valid.PSNR_E, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\EidorsPSNRMax}{%.2f}\n\n', max(T_valid.PSNR_E, [], 'omitnan'));

    % MATLAB metrics
    fprintf(fid, '%% MATLAB LBP\n');
    fprintf(fid, '\\newcommand{\\MatlabCCMean}{%.4f}\n', mean(T_valid.CC_M, 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabCCMin}{%.4f}\n', min(T_valid.CC_M, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabCCMax}{%.4f}\n', max(T_valid.CC_M, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabSSIMMean}{%.4f}\n', mean(T_valid.SSIM_M, 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabSSIMMin}{%.4f}\n', min(T_valid.SSIM_M, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabSSIMMax}{%.4f}\n', max(T_valid.SSIM_M, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabGREMean}{%.4f}\n', mean(T_valid.GRE_M, 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabGREMin}{%.4f}\n', min(T_valid.GRE_M, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabGREMax}{%.4f}\n', max(T_valid.GRE_M, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabRMSEMean}{%.4f}\n', mean(T_valid.RMSE_M, 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabRMSEMin}{%.4f}\n', min(T_valid.RMSE_M, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabRMSEMax}{%.4f}\n', max(T_valid.RMSE_M, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabPSNRMean}{%.2f}\n', mean(T_valid.PSNR_M, 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabPSNRMin}{%.2f}\n', min(T_valid.PSNR_M, [], 'omitnan'));
    fprintf(fid, '\\newcommand{\\MatlabPSNRMax}{%.2f}\n', max(T_valid.PSNR_M, [], 'omitnan'));

    fclose(fid);
end
